### ISSUE TITLE
This mod does not work...

### ISSUE THREAD

**Issue by agentwolf88** [TathanDev/StarWarsPlanets#2]
I use only the Beyond Earth Mod and Star Wars Planets but it does not work.

https://0x0.st/oafG.txt

**Comment by TathanDev** [comment]
Wich version of beyond Earth are you using ?

**Comment by TathanDev** [comment]
Ok i know the problem. 
For the moment, i use Beyond Earth 6.2-DEV but you use 6.1.
You need to use this version (Don't look the name, it is the the dev version) https://github.com/TathanDev/StarWarsPlanets/blob/main/libs/net/mrscauthd/beyond_earth/1.18.2-6.0/beyond_earth-1.18.2-6.0.jar

Thanks to report this issues^^

**Comment by agentwolf88** [comment]
THX 4 the info! Keep up your good work!
