### ISSUE TITLE
Crash with null point exception

### ISSUE THREAD

**Issue by TheRealM18** [TathanDev/StarWarsPlanets#4]
### Mod loader

Forge

### Minecraft version

1.18.2

### Star Wars Planets version

1.18.2-1.0.3 (Patch for working in current version of BE)

### Modloader version

40.1.25

### Modpack info

Custom Modpack, not issue

### The latest.log file

https://gist.github.com/TheRealM18/75eb8a626fd3220abbd2f3cc2049c7f2

### Issue description

If you have your mod, and BPD or demo mod, and leave on the change dimension screen,  You will not be able to get back in the game.  If it by itself, it is fine.  If it is BPD and demo, it is fine.

### Steps to reproduce

1. Install Demo, or Beyond Planets Dimensions
2. Install Star Wars Planets
3. Launch the game
4. go into single player
5. when your in galaxy window close the game
6. relaunch the game, and it will refuse to let you come into the game.

### Other information

MrScautHD, and I are not sure where this bug is coming from
[crash-2022-05-28_15.12.18-client.txt](https://github.com/TathanDev/StarWarsPlanets/files/8791696/crash-2022-05-28_15.12.18-client.txt)
[crash-2022-05-28_14.40.22-client.txt](https://github.com/TathanDev/StarWarsPlanets/files/8791697/crash-2022-05-28_14.40.22-client.txt)
[crash-2022-05-28_12.23.08-client.txt](https://github.com/TathanDev/StarWarsPlanets/files/8791698/crash-2022-05-28_12.23.08-client.txt)
[crash-2022-05-28_13.53.19-client.txt](https://github.com/TathanDev/StarWarsPlanets/files/8791699/crash-2022-05-28_13.53.19-client.txt)
[crash-2022-05-28_14.19.25-client.txt](https://github.com/TathanDev/StarWarsPlanets/files/8791700/crash-2022-05-28_14.19.25-client.txt)
.

**Comment by TheRealM18** [comment]
Fixed with pull request

**Comment by TathanDev** [comment]
Big thanks to MrScautHd and TheRealm18
